name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      uses: actions/setup-node@v1
      with:
       node-version: '10.x'
    - uses: actions/setup-python@v1
      name: Install Python
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install JupyterLab
    - run: python -m pip install jupyterlab
    - name: Build and run tests
      run: |
        npm install
        npm run build
        npm run test
