name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '10.x'
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install JupyterLab
      run: python -m pip install jupyterlab
    - name: Run tests
      run: |
        jlpm && jlpm run build
        jlpm run test
    - name: Browser check
      run: python -m jupyterlab.browser_check
